optimized DataBanner figure animation
charlieop/saga-homepage pull request #29
Opened 2024-12-02 16:49 UTC by CassieYXChen

2024-12-08 16:06 UTC, carriehxx approved these changes
Changes had been reviewed, no problem.

2024-12-09 01:44 UTC, o0-03 commented
Wow, so cool!

2024-12-09 05:30 UTC, charlieop requested changes
use document.querySelectAll() to select all the data-banner__block elements and use a forEach loop in js to add the listener. the actual value should be stored in html with data-value="VALUE".

2024-12-10 08:21 UTC, charlieop approved these changes

2024-12-10 08:21 UTC, merged